In [1]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk

In [2]:
tab_ds_atl=('tabulated_dataset/pacific.csv')
df=pd.read_csv('tabulated_dataset/pacific.csv')
df.head(15)

,ID,Name,Date,Time,Event,Status,Latitude,Longitude,Maximum Wind,Minimum Pressure,...,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,EP011949,UNNAMED,19490611,0,,TS,20.2N,106.3W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,EP011949,UNNAMED,19490611,600,,TS,20.2N,106.4W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,EP011949,UNNAMED,19490611,1200,,TS,20.2N,106.7W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,EP011949,UNNAMED,19490611,1800,,TS,20.3N,107.7W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,EP011949,UNNAMED,19490612,0,,TS,20.4N,108.6W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [18]:
df.head(20)

,ID,Name,Date,Time,Event,Status,Latitude,Longitude,Maximum Wind,Minimum Pressure,...,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,EP011949,UNNAMED,19490611,0,,TS,20.2N,106.3W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,EP011949,UNNAMED,19490611,600,,TS,20.2N,106.4W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,EP011949,UNNAMED,19490611,1200,,TS,20.2N,106.7W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,EP011949,UNNAMED,19490611,1800,,TS,20.3N,107.7W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,EP011949,UNNAMED,19490612,0,,TS,20.4N,108.6W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
5,EP011949,UNNAMED,19490612,600,,TS,20.5N,109.4W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
6,EP011949,UNNAMED,19490612,1200,,TS,20.6N,110.2W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
7,EP021949,UNNAMED,19490617,1200,,TS,14.1N,107.0W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
8,EP021949,UNNAMED,19490617,1800,,TS,14.6N,107.7W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
9,EP021949,UNNAMED,19490618,0,,TS,15.0N,108.4W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
10,EP021949,UNNAMED,19490618,600,,TS,15.4N,109.2W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
11,EP021949,UNNAMED,19490618,1200,,TS,15.7N,110.0W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
12,EP021949,UNNAMED,19490618,1800,,TS,16.0N,110.8W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
13,EP021949,UNNAMED,19490619,0,,TS,16.3N,111.6W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
14,EP021949,UNNAMED,19490619,600,,TS,16.7N,112.3W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
15,EP021949,UNNAMED,19490619,1200,,TS,17.1N,112.9W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
16,EP021949,UNNAMED,19490619,1800,,TS,17.5N,113.5W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
17,EP021949,UNNAMED,19490620,0,,TS,18.0N,114.1W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
18,EP021949,UNNAMED,19490620,600,,TS,18.4N,114.6W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
19,EP021949,UNNAMED,19490620,1200,,TS,18.9N,115.1W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [3]:
df.shape

(26137, 22)

In [4]:
# df.drop(['Name'], axis=1)
mdf=df.drop(['Status','ID','Name'],axis=1)
lat=mdf['Latitude']
lon=mdf['Longitude']
event=mdf['Event']
for i in range(len(list(lat))):
    lat[i]=float(lat[i][:-1])
    lon[i]=float(lon[i][:-1])
    event[i]=ord(event[i][0])
mdf

C:\Users\melod\AppData\Local\Temp\ipykernel_3036\3866280240.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lat[i]=float(lat[i][:-1])
C:\Users\melod\AppData\Local\Temp\ipykernel_3036\3866280240.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lon[i]=float(lon[i][:-1])
C:\Users\melod\AppData\Local\Temp\ipykernel_3036\3866280240.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  event[i]=ord(event[i][0])

,Date,Time,Event,Latitude,Longitude,Maximum Wind,Minimum Pressure,Low Wind NE,Low Wind SE,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,19490611,0,32,20.2,106.3,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,19490611,600,32,20.2,106.4,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,19490611,1200,32,20.2,106.7,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,19490611,1800,32,20.3,107.7,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,19490612,0,32,20.4,108.6,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26132,20151128,1200,32,21.7,109.0,35,1002,60,0,0,0,0,0,0,0,0,0,0,0
26133,20151128,1800,32,22.4,108.7,30,1007,0,0,0,0,0,0,0,0,0,0,0,0
26134,20151129,0,32,23.1,108.3,30,1008,0,0,0,0,0,0,0,0,0,0,0,0
26135,20151129,600,32,23.5,107.9,25,1009,0,0,0,0,0,0,0,0,0,0,0,0
26136,20151129,1200,32,24.2,107.7,20,1010,0,0,0,0,0,0,0,0,0,0,0,0

In [5]:
mdf

,Date,Time,Event,Latitude,Longitude,Maximum Wind,Minimum Pressure,Low Wind NE,Low Wind SE,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,19490611,0,32,20.2,106.3,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,19490611,600,32,20.2,106.4,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,19490611,1200,32,20.2,106.7,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,19490611,1800,32,20.3,107.7,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,19490612,0,32,20.4,108.6,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26132,20151128,1200,32,21.7,109.0,35,1002,60,0,0,0,0,0,0,0,0,0,0,0
26133,20151128,1800,32,22.4,108.7,30,1007,0,0,0,0,0,0,0,0,0,0,0,0
26134,20151129,0,32,23.1,108.3,30,1008,0,0,0,0,0,0,0,0,0,0,0,0
26135,20151129,600,32,23.5,107.9,25,1009,0,0,0,0,0,0,0,0,0,0,0,0
26136,20151129,1200,32,24.2,107.7,20,1010,0,0,0,0,0,0,0,0,0,0,0,0

In [6]:
x=mdf
y=df['Status']

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [8]:
x_train

,Date,Time,Event,Latitude,Longitude,Maximum Wind,Minimum Pressure,Low Wind NE,Low Wind SE,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
8329,19820718,600,32,16.5,150.4,35,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
13799,19910927,1800,32,15.5,122.5,95,961,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23643,20120712,1200,32,15.0,120.8,100,960,80,80,70,80,40,40,30,40,20,20,20,20
4011,19700715,600,32,16.3,111.5,40,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
16483,19960730,600,32,13.9,98.7,75,977,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13123,19900822,0,32,14.4,112.6,30,1009,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
19648,20030921,1800,32,20.1,109.4,65,987,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
9845,19840816,1800,32,9.2,150.1,30,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
10799,19851030,0,32,30.0,169.7,70,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2732,19660927,0,32,20.4,115.2,25,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [11]:
y_pred = classifier.predict(x_test)

C:\Users\melod\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [12]:
y_test

1834      HU
9445      HU
12727     TD
7539      HU
15517     TD
        ...
8513      TS
20267     TS
17071     TS
916       HU
20506     TS
Name: Status, Length: 5228, dtype: object

In [13]:
y_pred

array([' HU', ' HU', ' TD', ..., ' TS', ' HU', ' TS'], dtype=object)

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)

In [15]:
cm

array([[  31,    0,    0,    0,    0,   12,    0,    0,    0,    7,    0],
       [   0,   11,    0,    1,    0,    0,    0,    0,    0,   12,    6],
       [   0,    2,    6,    1,    0,    3,    0,    0,    0,    4,    3],
       [   0,    0,    0, 1312,    0,    0,    0,    0,    0,    0,   35],
       [   0,    0,    0,    1,    0,    0,    0,    0,    0,    0,    0],
       [  11,    0,    1,    0,    0,  282,    0,    0,    0,   68,    8],
       [   0,    0,    1,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    1,    0,    0,    1],
       [   0,    0,    0,    1,    0,    0,    0,    0,    0,    0,    0],
       [  14,    5,    1,    0,    0,   80,    0,    0,    0, 1263,   33],
       [   2,    0,    1,   31,    0,   12,    0,    0,    0,  146, 1819]],
      dtype=int64)

In [17]:
ac

0.903787299158378